config/routes.rb
# routes.rb
  Rails.application.routes.draw do
  # get 'inventory/list'
  root 'welcome#index'
  get 'inventory/list' => 'inventory#list'
  get 'inventory/:pid' => 'inventory#detail'


end

app/models/iteminv.rb
# item inventory this file
# labwk3/app/models/iteminv.rb
# make this file match the dot CSV file
# iteminv.rb
	class Iteminv

	attr_accessor  :pid, :item, :description, :price,
	 :condition, :dimension_w, :dimension_l, :dimension_h,
	  :img_file, :quantity, :category

	end


# where is the CSV file,
# douglasdrahem/myprojects/labwk3/data/mf_inventory
# how is that happening and WHY ???
# ask ? pass' to the inventory_controll.rb

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inventory_controller.rb
# reference 2032
# inventory_controller.rb
require 'csv'
# require "erb"
# require 'pp'

class InventoryController < ApplicationController

	def list
		@inventory = inventoryitems
	end
	def detail
		@inventory=inventoryitems
		@inventoryitem = @inventory.find{|inventoryitem| inventoryitem.pid == params[:pid]}
	end
	def inventoryitems
		@inventory = []

		CSV.foreach(Rails.root + 'data/mf_inventory.csv', headers: true) do |row|

			if row.to_h['quantity'].to_i > 0
			iteminv = Iteminv.new  # a new Class
				iteminv.pid = row.to_h['pid']
				iteminv.item = row.to_h['item']
				iteminv.description = row.to_h['description']
				iteminv.price = row.to_h['price']
				iteminv.condition = row.to_h['condition']
				iteminv.dimension_w = row.to_h['dimension_w']
				iteminv.dimension_l = row.to_h['dimension_l']
				iteminv.dimension_h = row.to_h['dimension_h']
				iteminv.img_file = row.to_h['img_file']
				iteminv.quantity = row.to_h['quantity']
				iteminv.category = row.to_h['category']
				@inventory << iteminv
			end # close do at CSV
		end
		@inventory
	end # close the defintion
end # close the CLASS

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inventory_helper.rb
module InventoryHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/inventory/detail.html.erb
<!-- detail.html.erb         -->
<h1>Mallory Furniture</h1>
<div class="navbuttons">
<%= link_to root_path, class:"homebutton" do %>
HOME
<% end %>
<%= link_to inventory_list_path, class:"backbutton" do %>
BACK
<% end %>
</div>

<div class="detailcontainer">
  <div class="loneimage">
    <%= image_tag "products/#{@inventoryitem.img_file}.jpg" %>
  </div>
  <div class="detailtable">
    <div class="tableitem">
      <%= @inventoryitem.item %>
    </div>
    <div class="priceline">
    <h4> Price </h4>
  </div>
    <div class="tableprice">
      <% if @inventoryitem.condition == "good" %>Clearance
        <%= number_to_currency @inventoryitem.price.to_i * 0.90 %>
      <% elsif @inventoryitem.condition == "average"  %>Clearance
        <%= number_to_currency @inventoryitem.price.to_i * 0.80 %>
      <% else %>
        <%= number_to_currency @inventoryitem.price %>
      <% end %>
    </div>
    <h5> Description </h5>
    <div class="csvdescription">
        <%= @inventoryitem.description %>
    </div>
      <h5> Dimensions </h5>
      <div class="wlh">
          <p1><span class="Width">Width: </span><%= @inventoryitem.dimension_w %> </p>
        <p1><span class="Width">Length: </span><%= @inventoryitem.dimension_l %> </p>
         <p1><span class="Width">Height: </span><%= @inventoryitem.dimension_h %> </p>
      </div>

  </div>
</div>

app/views/inventory/list.html.erb
<h1>Mallory Furniture</h1>
<div class="navbuttons">
<%= link_to root_path, class:"homebutton" do %>
HOME
<% end %>
<%= link_to inventory_list_path, class:"backbutton" do %>
BACK
<% end %>
</div>

<div class="outerwrap">
  <% @inventory.each do |inventory| %>
    <div class="itemtile">
      <div class="image">
        <%= image_tag "products/#{inventory.img_file}.jpg" %>
      </div>
      <div class="description">
      <%= inventory.item %>
      </div>
      <div class="price">
        <% if inventory.condition == "good" %><span class="Clearance">Clearance</span>
          <%= number_to_currency inventory.price.to_i * 0.90 %>
        <% elsif inventory.condition == "average"  %><span class="Clearance">Clearance</span>
          <%= number_to_currency inventory.price.to_i * 0.80 %>
        <% else %>
          <%= number_to_currency inventory.price %>
        <% end %>
      </div>
      <div>
        <a class="button" href="/inventory/<%= inventory.pid %>">More Info
      </a>
      </div>
    </div>
      <% inventory.quantity.to_s %>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Labwk3</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://necolas.github.io/normalize.css/3.0.3/normalize.css">
  <link href='https://fonts.googleapis.com/css?family=Shadows+Into+Light' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>Mallory Furniture</h1>
<!-- # <p><a href = "inventory/list"> Checkout our products </a></p> -->



<div class="widescreen">
  <div class="welcometextbox">
    <div class="yourfurn">
      <h3> Your Furniture is Old</h3>
    </div>
    <div class="ourfurn">
      <h2> Our's is Older</h2>
    </div>
    <div class="productbutton">
      <a href = "inventory/list"> Checkout our products </a>
    </div>
  </div>
<%= image_tag("hero.jpg", alt: "Welcome")%>
</div>